version: 1.2
tools:
  - subclass: CWL
    primaryDescriptorPath: /md5sum/dockstore-tool-md5sum.cwl # g
    testParameterFiles:
      - /md5sum/test-parameter-file-where-you-upload-own-md5sum-file.json
      - /md5sum/test-parameter-file-with-https-file.json
      - /md5sum/test-parameter-file-with-s3.json
    name: md5sum_test
    authors:
      - name: Flynn Hembroff

